-- MySQL Script generated by MySQL Workbench
-- Thu May  9 12:53:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema formulario_clientes
-- -----------------------------------------------------
-- Base de dados para os clientes

-- -----------------------------------------------------
-- Schema formulario_clientes
--
-- Base de dados para os clientes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `formulario_clientes` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ;
USE `formulario_clientes` ;

-- -----------------------------------------------------
-- Table `formulario_clientes`.`morada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formulario_clientes`.`morada` (
  `idmorada` INT NOT NULL,
  `provincia` VARCHAR(12) NOT NULL,
  `cidade` VARCHAR(35) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idmorada`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `formulario_clientes`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formulario_clientes`.`endereco` (
  `idendereco` INT NOT NULL,
  `telefone` VARCHAR(9) NOT NULL,
  `email` VARCHAR(35) CHARACTER SET 'binary' NOT NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `formulario_clientes`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formulario_clientes`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `idmorada` INT NOT NULL,
  `idendereco` INT NOT NULL,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`idcliente`, `idmorada`, `idendereco`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente`),
  INDEX `fk_cliente_morada_idx` (`idmorada` ),
  INDEX `fk_cliente_endereco1_idx` (`idendereco` ),
  CONSTRAINT `fk_cliente_morada`
    FOREIGN KEY (`idmorada`)
    REFERENCES `formulario_clientes`.`morada` (`idmorada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_endereco1`
    FOREIGN KEY (`idendereco`)
    REFERENCES `formulario_clientes`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4clientecliente
COLLATE = utf8mb4_unicode_520_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
